### ISSUE TITLE
java.sql.SQLException: Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by evollution** [schleyk/dockerfiles#9]
Hi, 
I am getting this error:
java.sql.SQLException: Unknown system variable 'query_cache_size'

when i try to connect guacamole to mysql8

Any idea how we could fi xthis ? 

I tried to update already to the latest mysql-connector-java but issue is still there

**Comment by schleyk** [comment]
Hi, 
can you please share more details about your setup?
Did you test the mariadb from the example docker-compose?

I never use guacamole together with mysql before, but I try to reproduce it.

**Comment by schleyk** [comment]
use mariadb fix this issue
